### PR TITLE
QuickSort

### PR DESCRIPTION
**Pull request by sid2631**
QuickSort

### CODE REVIEW

**Comment by sid2631** [comment]
QuickSort

**Comment by sachin-cpp** [comment]
Please add a pattern

**Comment by sid2631** [comment]
i write code for pattern can you accept this also

**Comment by prabalbansal6183** [comment]
Please done merge this sachin

**Comment by RaghavJindal13** [comment]
@sachin-cpp requesting you to please accept Patterns
Don't merge this PR

**Comment by Kr-Raman** [comment]
@sachin-cpp 
Only Patterns are accepted!

**Pull request closed without merging**
